id = "superhtml"
name = "Superhtml"
description = "Superhtml support."
version = "0.1.1"
schema_version = 1
authors = ["WeetHet <stas.ale66@gmail.com>", "sineptic <sineptic0@gmail.com>"]
repository = "https://github.com/WeetHet/superhtml-zed"

[[capabilities]]
kind = "process:exec"
command = "tar"
args = ["-xf", "**"]

[language_servers.superhtml]
name = "superhtml"
languages = ["HTML", "SuperHTML"]

[grammars.superhtml]
repository = "https://github.com/kristoff-it/superhtml"
commit = "48c3d2285d6c95bbcfb4055c8c84a2c1079fb2aa"
path = "tree-sitter-superhtml"
